# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.one_tap_callback_post200_response import OneTapCallbackPost200Response

class TestOneTapCallbackPost200Response(unittest.TestCase):
    """OneTapCallbackPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OneTapCallbackPost200Response:
        """Test OneTapCallbackPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OneTapCallbackPost200Response`
        """
        model = OneTapCallbackPost200Response()
        if include_optional:
            return OneTapCallbackPost200Response(
                session = better_auth.models.session.Session(
                    id = '', 
                    expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    token = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    ip_address = '', 
                    user_agent = '', 
                    user_id = '', 
                    impersonated_by = '', ),
                user = better_auth.models.user.User(
                    id = '', 
                    name = '', 
                    email = '', 
                    email_verified = True, 
                    image = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    two_factor_enabled = True, 
                    role = '', 
                    banned = True, 
                    ban_reason = '', 
                    ban_expires = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return OneTapCallbackPost200Response(
        )
        """

    def testOneTapCallbackPost200Response(self):
        """Test OneTapCallbackPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
