# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.passkey_update_passkey_post_request import PasskeyUpdatePasskeyPostRequest

class TestPasskeyUpdatePasskeyPostRequest(unittest.TestCase):
    """PasskeyUpdatePasskeyPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PasskeyUpdatePasskeyPostRequest:
        """Test PasskeyUpdatePasskeyPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PasskeyUpdatePasskeyPostRequest`
        """
        model = PasskeyUpdatePasskeyPostRequest()
        if include_optional:
            return PasskeyUpdatePasskeyPostRequest(
                id = '',
                name = ''
            )
        else:
            return PasskeyUpdatePasskeyPostRequest(
                id = '',
                name = '',
        )
        """

    def testPasskeyUpdatePasskeyPostRequest(self):
        """Test PasskeyUpdatePasskeyPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
