# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.reset_password_callback200_response import ResetPasswordCallback200Response

class TestResetPasswordCallback200Response(unittest.TestCase):
    """ResetPasswordCallback200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResetPasswordCallback200Response:
        """Test ResetPasswordCallback200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResetPasswordCallback200Response`
        """
        model = ResetPasswordCallback200Response()
        if include_optional:
            return ResetPasswordCallback200Response(
                token = ''
            )
        else:
            return ResetPasswordCallback200Response(
        )
        """

    def testResetPasswordCallback200Response(self):
        """Test ResetPasswordCallback200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
