# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.link_social_account_request import LinkSocialAccountRequest

class TestLinkSocialAccountRequest(unittest.TestCase):
    """LinkSocialAccountRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkSocialAccountRequest:
        """Test LinkSocialAccountRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkSocialAccountRequest`
        """
        model = LinkSocialAccountRequest()
        if include_optional:
            return LinkSocialAccountRequest(
                callback_url = '',
                provider = '',
                id_token = better_auth.models.link_social_account_request_id_token.linkSocialAccount_request_idToken(
                    token = '', 
                    nonce = '', 
                    access_token = '', 
                    refresh_token = '', 
                    scopes = [
                        null
                        ], ),
                request_sign_up = True,
                scopes = [
                    null
                    ],
                error_callback_url = '',
                disable_redirect = True,
                additional_data = ''
            )
        else:
            return LinkSocialAccountRequest(
                provider = '',
        )
        """

    def testLinkSocialAccountRequest(self):
        """Test LinkSocialAccountRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
