# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.account_info_get200_response_user import AccountInfoGet200ResponseUser

class TestAccountInfoGet200ResponseUser(unittest.TestCase):
    """AccountInfoGet200ResponseUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountInfoGet200ResponseUser:
        """Test AccountInfoGet200ResponseUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountInfoGet200ResponseUser`
        """
        model = AccountInfoGet200ResponseUser()
        if include_optional:
            return AccountInfoGet200ResponseUser(
                id = '',
                name = '',
                email = '',
                image = '',
                email_verified = True
            )
        else:
            return AccountInfoGet200ResponseUser(
                id = '',
                email_verified = True,
        )
        """

    def testAccountInfoGet200ResponseUser(self):
        """Test AccountInfoGet200ResponseUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
