# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.admin_list_user_sessions200_response import AdminListUserSessions200Response

class TestAdminListUserSessions200Response(unittest.TestCase):
    """AdminListUserSessions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminListUserSessions200Response:
        """Test AdminListUserSessions200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminListUserSessions200Response`
        """
        model = AdminListUserSessions200Response()
        if include_optional:
            return AdminListUserSessions200Response(
                sessions = [
                    better_auth.models.session.Session(
                        id = '', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        token = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        ip_address = '', 
                        user_agent = '', 
                        user_id = '', 
                        impersonated_by = '', )
                    ]
            )
        else:
            return AdminListUserSessions200Response(
        )
        """

    def testAdminListUserSessions200Response(self):
        """Test AdminListUserSessions200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
