# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.social_sign_in_request_id_token import SocialSignInRequestIdToken

class TestSocialSignInRequestIdToken(unittest.TestCase):
    """SocialSignInRequestIdToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SocialSignInRequestIdToken:
        """Test SocialSignInRequestIdToken
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SocialSignInRequestIdToken`
        """
        model = SocialSignInRequestIdToken()
        if include_optional:
            return SocialSignInRequestIdToken(
                token = '',
                nonce = '',
                access_token = '',
                refresh_token = '',
                expires_at = 1.337
            )
        else:
            return SocialSignInRequestIdToken(
                token = '',
        )
        """

    def testSocialSignInRequestIdToken(self):
        """Test SocialSignInRequestIdToken"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
