# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.api.api_key_api import ApiKeyApi


class TestApiKeyApi(unittest.TestCase):
    """ApiKeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiKeyApi()

    def tearDown(self) -> None:
        pass

    def test_api_key_create_post(self) -> None:
        """Test case for api_key_create_post

        """
        pass

    def test_api_key_delete_post(self) -> None:
        """Test case for api_key_delete_post

        """
        pass

    def test_api_key_get_get(self) -> None:
        """Test case for api_key_get_get

        """
        pass

    def test_api_key_list_get(self) -> None:
        """Test case for api_key_list_get

        """
        pass

    def test_api_key_update_post(self) -> None:
        """Test case for api_key_update_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
