# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.refresh_token_post200_response import RefreshTokenPost200Response

class TestRefreshTokenPost200Response(unittest.TestCase):
    """RefreshTokenPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefreshTokenPost200Response:
        """Test RefreshTokenPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefreshTokenPost200Response`
        """
        model = RefreshTokenPost200Response()
        if include_optional:
            return RefreshTokenPost200Response(
                token_type = '',
                id_token = '',
                access_token = '',
                refresh_token = '',
                access_token_expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                refresh_token_expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return RefreshTokenPost200Response(
        )
        """

    def testRefreshTokenPost200Response(self):
        """Test RefreshTokenPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
