# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.api_key_create_post_request import ApiKeyCreatePostRequest

class TestApiKeyCreatePostRequest(unittest.TestCase):
    """ApiKeyCreatePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyCreatePostRequest:
        """Test ApiKeyCreatePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyCreatePostRequest`
        """
        model = ApiKeyCreatePostRequest()
        if include_optional:
            return ApiKeyCreatePostRequest(
                name = '',
                expires_in = '',
                user_id = '',
                prefix = '',
                remaining = '',
                metadata = '',
                refill_amount = 1.337,
                refill_interval = 1.337,
                rate_limit_time_window = 1.337,
                rate_limit_max = 1.337,
                rate_limit_enabled = True,
                permissions = ''
            )
        else:
            return ApiKeyCreatePostRequest(
                expires_in = '',
                remaining = '',
        )
        """

    def testApiKeyCreatePostRequest(self):
        """Test ApiKeyCreatePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
