# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.passkey_generate_authenticate_options200_response import PasskeyGenerateAuthenticateOptions200Response

class TestPasskeyGenerateAuthenticateOptions200Response(unittest.TestCase):
    """PasskeyGenerateAuthenticateOptions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PasskeyGenerateAuthenticateOptions200Response:
        """Test PasskeyGenerateAuthenticateOptions200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PasskeyGenerateAuthenticateOptions200Response`
        """
        model = PasskeyGenerateAuthenticateOptions200Response()
        if include_optional:
            return PasskeyGenerateAuthenticateOptions200Response(
                challenge = '',
                rp = better_auth.models.generate_passkey_registration_options_200_response_rp.generatePasskeyRegistrationOptions_200_response_rp(
                    name = '', 
                    id = '', ),
                user = better_auth.models.generate_passkey_registration_options_200_response_user.generatePasskeyRegistrationOptions_200_response_user(
                    id = '', 
                    name = '', 
                    display_name = '', ),
                timeout = 1.337,
                allow_credentials = [
                    better_auth.models.generate_passkey_registration_options_200_response_exclude_credentials_inner.generatePasskeyRegistrationOptions_200_response_excludeCredentials_inner(
                        id = '', 
                        type = '', 
                        transports = [
                            ''
                            ], )
                    ],
                user_verification = '',
                authenticator_selection = better_auth.models.generate_passkey_registration_options_200_response_authenticator_selection.generatePasskeyRegistrationOptions_200_response_authenticatorSelection(
                    authenticator_attachment = '', 
                    require_resident_key = True, 
                    user_verification = '', ),
                extensions = None
            )
        else:
            return PasskeyGenerateAuthenticateOptions200Response(
        )
        """

    def testPasskeyGenerateAuthenticateOptions200Response(self):
        """Test PasskeyGenerateAuthenticateOptions200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
