# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.two_factor_verify_backup_code_post_request import TwoFactorVerifyBackupCodePostRequest

class TestTwoFactorVerifyBackupCodePostRequest(unittest.TestCase):
    """TwoFactorVerifyBackupCodePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TwoFactorVerifyBackupCodePostRequest:
        """Test TwoFactorVerifyBackupCodePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TwoFactorVerifyBackupCodePostRequest`
        """
        model = TwoFactorVerifyBackupCodePostRequest()
        if include_optional:
            return TwoFactorVerifyBackupCodePostRequest(
                code = '',
                disable_session = True,
                trust_device = True
            )
        else:
            return TwoFactorVerifyBackupCodePostRequest(
                code = '',
        )
        """

    def testTwoFactorVerifyBackupCodePostRequest(self):
        """Test TwoFactorVerifyBackupCodePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
