# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.admin_set_user_role_request import AdminSetUserRoleRequest

class TestAdminSetUserRoleRequest(unittest.TestCase):
    """AdminSetUserRoleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminSetUserRoleRequest:
        """Test AdminSetUserRoleRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminSetUserRoleRequest`
        """
        model = AdminSetUserRoleRequest()
        if include_optional:
            return AdminSetUserRoleRequest(
                user_id = '',
                role = ''
            )
        else:
            return AdminSetUserRoleRequest(
                user_id = '',
                role = '',
        )
        """

    def testAdminSetUserRoleRequest(self):
        """Test AdminSetUserRoleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
