# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.passkey import Passkey

class TestPasskey(unittest.TestCase):
    """Passkey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Passkey:
        """Test Passkey
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Passkey`
        """
        model = Passkey()
        if include_optional:
            return Passkey(
                id = '',
                name = '',
                public_key = '',
                user_id = '',
                credential_id = '',
                counter = 1.337,
                device_type = '',
                backed_up = True,
                transports = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                aaguid = ''
            )
        else:
            return Passkey(
                public_key = '',
                user_id = '',
                credential_id = '',
                counter = 1.337,
                device_type = '',
                backed_up = True,
        )
        """

    def testPasskey(self):
        """Test Passkey"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
