# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.generate_passkey_registration_options200_response_exclude_credentials_inner import GeneratePasskeyRegistrationOptions200ResponseExcludeCredentialsInner

class TestGeneratePasskeyRegistrationOptions200ResponseExcludeCredentialsInner(unittest.TestCase):
    """GeneratePasskeyRegistrationOptions200ResponseExcludeCredentialsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeneratePasskeyRegistrationOptions200ResponseExcludeCredentialsInner:
        """Test GeneratePasskeyRegistrationOptions200ResponseExcludeCredentialsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeneratePasskeyRegistrationOptions200ResponseExcludeCredentialsInner`
        """
        model = GeneratePasskeyRegistrationOptions200ResponseExcludeCredentialsInner()
        if include_optional:
            return GeneratePasskeyRegistrationOptions200ResponseExcludeCredentialsInner(
                id = '',
                type = '',
                transports = [
                    ''
                    ]
            )
        else:
            return GeneratePasskeyRegistrationOptions200ResponseExcludeCredentialsInner(
        )
        """

    def testGeneratePasskeyRegistrationOptions200ResponseExcludeCredentialsInner(self):
        """Test GeneratePasskeyRegistrationOptions200ResponseExcludeCredentialsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
