# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.two_factor_generate_backup_codes_post_request import TwoFactorGenerateBackupCodesPostRequest

class TestTwoFactorGenerateBackupCodesPostRequest(unittest.TestCase):
    """TwoFactorGenerateBackupCodesPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TwoFactorGenerateBackupCodesPostRequest:
        """Test TwoFactorGenerateBackupCodesPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TwoFactorGenerateBackupCodesPostRequest`
        """
        model = TwoFactorGenerateBackupCodesPostRequest()
        if include_optional:
            return TwoFactorGenerateBackupCodesPostRequest(
                password = ''
            )
        else:
            return TwoFactorGenerateBackupCodesPostRequest(
                password = '',
        )
        """

    def testTwoFactorGenerateBackupCodesPostRequest(self):
        """Test TwoFactorGenerateBackupCodesPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
