# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.social_sign_in400_response import SocialSignIn400Response

class TestSocialSignIn400Response(unittest.TestCase):
    """SocialSignIn400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SocialSignIn400Response:
        """Test SocialSignIn400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SocialSignIn400Response`
        """
        model = SocialSignIn400Response()
        if include_optional:
            return SocialSignIn400Response(
                message = ''
            )
        else:
            return SocialSignIn400Response(
                message = '',
        )
        """

    def testSocialSignIn400Response(self):
        """Test SocialSignIn400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
