# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.api_key_create_post200_response import ApiKeyCreatePost200Response

class TestApiKeyCreatePost200Response(unittest.TestCase):
    """ApiKeyCreatePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyCreatePost200Response:
        """Test ApiKeyCreatePost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyCreatePost200Response`
        """
        model = ApiKeyCreatePost200Response()
        if include_optional:
            return ApiKeyCreatePost200Response(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                prefix = '',
                start = '',
                key = '',
                enabled = True,
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                user_id = '',
                last_refill_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_request = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                metadata = {
                    'key' : null
                    },
                rate_limit_max = 1.337,
                rate_limit_time_window = 1.337,
                remaining = 1.337,
                refill_amount = 1.337,
                refill_interval = 1.337,
                rate_limit_enabled = True,
                request_count = 1.337,
                permissions = {
                    'key' : [
                        ''
                        ]
                    }
            )
        else:
            return ApiKeyCreatePost200Response(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                key = '',
                enabled = True,
                user_id = '',
                rate_limit_enabled = True,
                request_count = 1.337,
        )
        """

    def testApiKeyCreatePost200Response(self):
        """Test ApiKeyCreatePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
