# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.one_tap_callback_post_request import OneTapCallbackPostRequest

class TestOneTapCallbackPostRequest(unittest.TestCase):
    """OneTapCallbackPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OneTapCallbackPostRequest:
        """Test OneTapCallbackPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OneTapCallbackPostRequest`
        """
        model = OneTapCallbackPostRequest()
        if include_optional:
            return OneTapCallbackPostRequest(
                id_token = ''
            )
        else:
            return OneTapCallbackPostRequest(
                id_token = '',
        )
        """

    def testOneTapCallbackPostRequest(self):
        """Test OneTapCallbackPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
