# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.sign_up_with_email_and_password_request import SignUpWithEmailAndPasswordRequest

class TestSignUpWithEmailAndPasswordRequest(unittest.TestCase):
    """SignUpWithEmailAndPasswordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignUpWithEmailAndPasswordRequest:
        """Test SignUpWithEmailAndPasswordRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignUpWithEmailAndPasswordRequest`
        """
        model = SignUpWithEmailAndPasswordRequest()
        if include_optional:
            return SignUpWithEmailAndPasswordRequest(
                name = '',
                email = '',
                password = '',
                image = '',
                callback_url = '',
                remember_me = True
            )
        else:
            return SignUpWithEmailAndPasswordRequest(
                name = '',
                email = '',
                password = '',
        )
        """

    def testSignUpWithEmailAndPasswordRequest(self):
        """Test SignUpWithEmailAndPasswordRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
