# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.sign_in_email_request import SignInEmailRequest

class TestSignInEmailRequest(unittest.TestCase):
    """SignInEmailRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignInEmailRequest:
        """Test SignInEmailRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignInEmailRequest`
        """
        model = SignInEmailRequest()
        if include_optional:
            return SignInEmailRequest(
                email = '',
                password = '',
                callback_url = '',
                remember_me = ''
            )
        else:
            return SignInEmailRequest(
                email = '',
                password = '',
        )
        """

    def testSignInEmailRequest(self):
        """Test SignInEmailRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
