# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.two_factor_verify_otp_post_request import TwoFactorVerifyOtpPostRequest

class TestTwoFactorVerifyOtpPostRequest(unittest.TestCase):
    """TwoFactorVerifyOtpPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TwoFactorVerifyOtpPostRequest:
        """Test TwoFactorVerifyOtpPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TwoFactorVerifyOtpPostRequest`
        """
        model = TwoFactorVerifyOtpPostRequest()
        if include_optional:
            return TwoFactorVerifyOtpPostRequest(
                code = '',
                trust_device = True
            )
        else:
            return TwoFactorVerifyOtpPostRequest(
                code = '',
        )
        """

    def testTwoFactorVerifyOtpPostRequest(self):
        """Test TwoFactorVerifyOtpPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
