# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.api.one_tap_api import OneTapApi


class TestOneTapApi(unittest.TestCase):
    """OneTapApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OneTapApi()

    def tearDown(self) -> None:
        pass

    def test_one_tap_callback_post(self) -> None:
        """Test case for one_tap_callback_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
