# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.passkey_update_passkey_post200_response import PasskeyUpdatePasskeyPost200Response

class TestPasskeyUpdatePasskeyPost200Response(unittest.TestCase):
    """PasskeyUpdatePasskeyPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PasskeyUpdatePasskeyPost200Response:
        """Test PasskeyUpdatePasskeyPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PasskeyUpdatePasskeyPost200Response`
        """
        model = PasskeyUpdatePasskeyPost200Response()
        if include_optional:
            return PasskeyUpdatePasskeyPost200Response(
                passkey = better_auth.models.passkey.Passkey(
                    id = '', 
                    name = '', 
                    public_key = '', 
                    user_id = '', 
                    credential_id = '', 
                    counter = 1.337, 
                    device_type = '', 
                    backed_up = True, 
                    transports = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    aaguid = '', )
            )
        else:
            return PasskeyUpdatePasskeyPost200Response(
                passkey = better_auth.models.passkey.Passkey(
                    id = '', 
                    name = '', 
                    public_key = '', 
                    user_id = '', 
                    credential_id = '', 
                    counter = 1.337, 
                    device_type = '', 
                    backed_up = True, 
                    transports = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    aaguid = '', ),
        )
        """

    def testPasskeyUpdatePasskeyPost200Response(self):
        """Test PasskeyUpdatePasskeyPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
