# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.api_key_delete_post200_response import ApiKeyDeletePost200Response

class TestApiKeyDeletePost200Response(unittest.TestCase):
    """ApiKeyDeletePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyDeletePost200Response:
        """Test ApiKeyDeletePost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyDeletePost200Response`
        """
        model = ApiKeyDeletePost200Response()
        if include_optional:
            return ApiKeyDeletePost200Response(
                success = True
            )
        else:
            return ApiKeyDeletePost200Response(
                success = True,
        )
        """

    def testApiKeyDeletePost200Response(self):
        """Test ApiKeyDeletePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
