# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.api_key_get_get200_response import ApiKeyGetGet200Response

class TestApiKeyGetGet200Response(unittest.TestCase):
    """ApiKeyGetGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyGetGet200Response:
        """Test ApiKeyGetGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyGetGet200Response`
        """
        model = ApiKeyGetGet200Response()
        if include_optional:
            return ApiKeyGetGet200Response(
                id = '',
                name = '',
                start = '',
                prefix = '',
                user_id = '',
                refill_interval = 1.337,
                refill_amount = 1.337,
                last_refill_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                enabled = True,
                rate_limit_enabled = True,
                rate_limit_time_window = 1.337,
                rate_limit_max = 1.337,
                request_count = 1.337,
                remaining = 1.337,
                last_request = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                metadata = {
                    'key' : null
                    },
                permissions = ''
            )
        else:
            return ApiKeyGetGet200Response(
                id = '',
                user_id = '',
                enabled = True,
                rate_limit_enabled = True,
                request_count = 1.337,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testApiKeyGetGet200Response(self):
        """Test ApiKeyGetGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
