# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.sign_up_with_email_and_password200_response_user import SignUpWithEmailAndPassword200ResponseUser

class TestSignUpWithEmailAndPassword200ResponseUser(unittest.TestCase):
    """SignUpWithEmailAndPassword200ResponseUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignUpWithEmailAndPassword200ResponseUser:
        """Test SignUpWithEmailAndPassword200ResponseUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignUpWithEmailAndPassword200ResponseUser`
        """
        model = SignUpWithEmailAndPassword200ResponseUser()
        if include_optional:
            return SignUpWithEmailAndPassword200ResponseUser(
                id = '',
                email = '',
                name = '',
                image = '',
                email_verified = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return SignUpWithEmailAndPassword200ResponseUser(
                id = '',
                email = '',
                name = '',
                email_verified = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testSignUpWithEmailAndPassword200ResponseUser(self):
        """Test SignUpWithEmailAndPassword200ResponseUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
