# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.send_verification_email200_response import SendVerificationEmail200Response

class TestSendVerificationEmail200Response(unittest.TestCase):
    """SendVerificationEmail200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendVerificationEmail200Response:
        """Test SendVerificationEmail200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendVerificationEmail200Response`
        """
        model = SendVerificationEmail200Response()
        if include_optional:
            return SendVerificationEmail200Response(
                status = True
            )
        else:
            return SendVerificationEmail200Response(
        )
        """

    def testSendVerificationEmail200Response(self):
        """Test SendVerificationEmail200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
