# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.two_factor_verify_otp_post200_response import TwoFactorVerifyOtpPost200Response

class TestTwoFactorVerifyOtpPost200Response(unittest.TestCase):
    """TwoFactorVerifyOtpPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TwoFactorVerifyOtpPost200Response:
        """Test TwoFactorVerifyOtpPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TwoFactorVerifyOtpPost200Response`
        """
        model = TwoFactorVerifyOtpPost200Response()
        if include_optional:
            return TwoFactorVerifyOtpPost200Response(
                token = '',
                user = better_auth.models._two_factor_verify_otp_post_200_response_user._two_factor_verify_otp_post_200_response_user(
                    id = '', 
                    email = '', 
                    email_verified = True, 
                    name = '', 
                    image = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return TwoFactorVerifyOtpPost200Response(
                token = '',
                user = better_auth.models._two_factor_verify_otp_post_200_response_user._two_factor_verify_otp_post_200_response_user(
                    id = '', 
                    email = '', 
                    email_verified = True, 
                    name = '', 
                    image = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testTwoFactorVerifyOtpPost200Response(self):
        """Test TwoFactorVerifyOtpPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
