# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.apikey import Apikey

class TestApikey(unittest.TestCase):
    """Apikey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Apikey:
        """Test Apikey
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Apikey`
        """
        model = Apikey()
        if include_optional:
            return Apikey(
                id = '',
                name = '',
                start = '',
                prefix = '',
                key = '',
                user_id = '',
                refill_interval = 1.337,
                refill_amount = 1.337,
                last_refill_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                enabled = True,
                rate_limit_enabled = True,
                rate_limit_time_window = 1.337,
                rate_limit_max = 1.337,
                request_count = 1.337,
                remaining = 1.337,
                last_request = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                permissions = '',
                metadata = ''
            )
        else:
            return Apikey(
        )
        """

    def testApikey(self):
        """Test Apikey"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
