# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.generate_passkey_registration_options200_response_authenticator_selection import GeneratePasskeyRegistrationOptions200ResponseAuthenticatorSelection

class TestGeneratePasskeyRegistrationOptions200ResponseAuthenticatorSelection(unittest.TestCase):
    """GeneratePasskeyRegistrationOptions200ResponseAuthenticatorSelection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeneratePasskeyRegistrationOptions200ResponseAuthenticatorSelection:
        """Test GeneratePasskeyRegistrationOptions200ResponseAuthenticatorSelection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeneratePasskeyRegistrationOptions200ResponseAuthenticatorSelection`
        """
        model = GeneratePasskeyRegistrationOptions200ResponseAuthenticatorSelection()
        if include_optional:
            return GeneratePasskeyRegistrationOptions200ResponseAuthenticatorSelection(
                authenticator_attachment = '',
                require_resident_key = True,
                user_verification = ''
            )
        else:
            return GeneratePasskeyRegistrationOptions200ResponseAuthenticatorSelection(
        )
        """

    def testGeneratePasskeyRegistrationOptions200ResponseAuthenticatorSelection(self):
        """Test GeneratePasskeyRegistrationOptions200ResponseAuthenticatorSelection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
