# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.generate_passkey_registration_options200_response_rp import GeneratePasskeyRegistrationOptions200ResponseRp

class TestGeneratePasskeyRegistrationOptions200ResponseRp(unittest.TestCase):
    """GeneratePasskeyRegistrationOptions200ResponseRp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeneratePasskeyRegistrationOptions200ResponseRp:
        """Test GeneratePasskeyRegistrationOptions200ResponseRp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeneratePasskeyRegistrationOptions200ResponseRp`
        """
        model = GeneratePasskeyRegistrationOptions200ResponseRp()
        if include_optional:
            return GeneratePasskeyRegistrationOptions200ResponseRp(
                name = '',
                id = ''
            )
        else:
            return GeneratePasskeyRegistrationOptions200ResponseRp(
        )
        """

    def testGeneratePasskeyRegistrationOptions200ResponseRp(self):
        """Test GeneratePasskeyRegistrationOptions200ResponseRp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
