# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.two_factor_enable_post200_response import TwoFactorEnablePost200Response

class TestTwoFactorEnablePost200Response(unittest.TestCase):
    """TwoFactorEnablePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TwoFactorEnablePost200Response:
        """Test TwoFactorEnablePost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TwoFactorEnablePost200Response`
        """
        model = TwoFactorEnablePost200Response()
        if include_optional:
            return TwoFactorEnablePost200Response(
                totp_uri = '',
                backup_codes = [
                    ''
                    ]
            )
        else:
            return TwoFactorEnablePost200Response(
        )
        """

    def testTwoFactorEnablePost200Response(self):
        """Test TwoFactorEnablePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
