# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.link_social_account_request_id_token import LinkSocialAccountRequestIdToken

class TestLinkSocialAccountRequestIdToken(unittest.TestCase):
    """LinkSocialAccountRequestIdToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkSocialAccountRequestIdToken:
        """Test LinkSocialAccountRequestIdToken
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkSocialAccountRequestIdToken`
        """
        model = LinkSocialAccountRequestIdToken()
        if include_optional:
            return LinkSocialAccountRequestIdToken(
                token = '',
                nonce = '',
                access_token = '',
                refresh_token = '',
                scopes = [
                    null
                    ]
            )
        else:
            return LinkSocialAccountRequestIdToken(
                token = '',
        )
        """

    def testLinkSocialAccountRequestIdToken(self):
        """Test LinkSocialAccountRequestIdToken"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
