# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from better_auth.models.api_key_update_post_request import ApiKeyUpdatePostRequest

class TestApiKeyUpdatePostRequest(unittest.TestCase):
    """ApiKeyUpdatePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyUpdatePostRequest:
        """Test ApiKeyUpdatePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyUpdatePostRequest`
        """
        model = ApiKeyUpdatePostRequest()
        if include_optional:
            return ApiKeyUpdatePostRequest(
                key_id = '',
                user_id = '',
                name = '',
                enabled = True,
                remaining = 1.337,
                refill_amount = 1.337,
                refill_interval = 1.337,
                metadata = '',
                expires_in = '',
                rate_limit_enabled = True,
                rate_limit_time_window = 1.337,
                rate_limit_max = 1.337,
                permissions = ''
            )
        else:
            return ApiKeyUpdatePostRequest(
                key_id = '',
                expires_in = '',
                permissions = '',
        )
        """

    def testApiKeyUpdatePostRequest(self):
        """Test ApiKeyUpdatePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
