# coding: utf-8

"""
    Better Auth

    API Reference for your Better Auth Instance

    The version of the OpenAPI document: 1.1.0
    Contact: chasenspace@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "better-auth"
VERSION = "0.0.1-beta8"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Python SDK for better-auth - generated by OpenAPI Generator",
    author="Chasen Gao",
    author_email="chasenspace@gmail.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Better Auth"],
    install_requires=REQUIRES,
    packages=find_packages(where="src", exclude=["test", "tests"]),
    package_dir={"": "src"},
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    API Reference for your Better Auth Instance
    """,  # noqa: E501
    package_data={"better_auth": ["py.typed"]},
)